version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: source/conf.py

# Optionally build your docs in additional formats such as PDF
formats:
  - pdf

python:
  version: 3.12.0
  install:
    - requirements: requirements.txt
